name: gapslp
version: 0.1
date: 02/04/2017
description: SLP for free groups

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent
    - name: Juliette Ortholand

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://laurentbartholdi.github.io/gapslp/
readme: https://laurentbartholdi.github.io/gapslp/README.md
packageinfo: https://laurentbartholdi.github.io/gapslp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/laurentbartholdi/gapslp/releases/download/v0.1/gapslp-0.1.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
